### ISSUE TITLE
Read/write DataFrames from/to Parquet files

### ISSUE THREAD

**Issue by andrus** [dflib/dflib#117]
It is about time we start supporting Parquet format. Parquet Java library (`parquet-avro`) is not particularly friendly for standalone use outside Hadoop, but looks like it is changing. Version 1.14.0 is almost decoupled from Hadoop

**Comment by andrus** [comment]
This effort may depend on #118.

**Comment by hoggatt** [comment]
Hey, just stumbled on this project since it seems that tablesaw is dead, dead. It looks great and I really like some of the optimizations being done (like parallelizing row operations). 

This would be the issue that would get us to start trying to use this library. We use the parquet format a lot since it has wide support with other languages (like python and matlab) and compresses medium datasets quite well.

**Comment by andrus** [comment]
Hi @hoggatt , thanks for the note. Yeah, Parquet support is one of the priorities now. It is going to happen.

**Comment by andrus** [comment]
The basic loader / saver is done. Import `dflib-parquet` module and use `Parquet` class to access both.
